# -*- coding: utf-8 -*-
"""Unemployment_2.ipynb

Automatically generated by Colaboratory.

# ***UNEMPLOYMENT ANALYSIS***
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import plotly.express as px
import warnings

path ='/content/drive/MyDrive/DATASETS/Unemployment_Rate_upto_11_2020.csv'

unemp_df = pd.read_csv(path)

"""## ***DATA INSPECTION***"""

unemp_df.head()

unemp_df.tail()

unemp_df.info()

unemp_df.isnull().sum()

unemp_df.shape

unemp_nw = unemp_df.dropna()

unemp_nw

unemp_nw.duplicated().sum()

unemp_nw.columns = ['States' , 'Date', 'Frequency','Estimated Unemployment Rate', 'Estimated Employed', 'Estimated Labour Participation Rate', 'Region','Longitude', 'Latitude']

"""### ***Statistical Analysis***"""

unemp_df.describe()

"""## ***HEAT MAP***"""

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(10,10))
sns.heatmap(unemp_nw.corr())
plt.show()

sns.countplot(x=unemp_nw['States'],palette = "Set2")
plt.xticks(rotation='vertical')
plt.show()

sns.countplot(x=unemp_nw['Region'],palette = "Set1")
plt.xticks(rotation='vertical')
plt.show()

"""***VISUALIZING UNEMPLOYMENT RATE IN DIFFERENT REGIONS***"""

unemp_nw.columns = ['States' , 'Date', 'Frequency','Estimated Unemployment Rate', 'Estimated Employed', 'Estimated Labour Participation Rate', 'Region','Longitude', 'Latitude'] 
plt.title("Indian Unemployment according to Region")
sns.histplot(x= "Estimated Employed" , hue="Region" , data=unemp_nw)

"""***VISUALIZING UNEMPLOYMENT RATE IN DIFFERENT STATES***"""

fig = px.bar(unemp_nw, x= 'States', y = 'Estimated Unemployment Rate' , color = 'States' , title = 'Unemployment Rate in Each State' , template = 'plotly')
fig.update_layout(xaxis= {'categoryorder' : 'total descending'})
fig.show()

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.axis('equal')
l = ["Estimated Unemployment Rate", "Estimated Employed" , "Estimates Labour Participation Rate"]
s = [50,50,50]
ax.pie(s,labels= l, autopct = '%1.2f%%')
plt.show()

sns.set(style = "darkgrid")
unemp_nw.hist()
plt.show()

pip install -U kaleido

fig = px.scatter_3d(unemp_nw , x = 'Date', y = 'Estimated Unemployment Rate' , z= 'Region' , color = 'Region')
fig.show()
fig.write_image('3d.png')

unemp = unemp_nw[["States", "Region", "Estimated Unemployment Rate"]]
figure = px.sunburst(unemp , path = ["Region", "States"],
                     values = "Estimated Unemployment Rate",
                     width = 700 , height = 700, color_continuous_scale = "RdY1Gn", title = "Unemployment Rate in India")
figure.show()

unemp_nw.corr()

unemp_nw['States'].unique()

sns.pairplot(unemp_nw , height = 2.7 , aspect = 1.5 , diag_kws={'color':'red'} , plot_kws = {'color':'green'})
plt.show()

fig = plt.figure(figsize = (20,8))
ax = sns.lineplot(y = 'Estimated Unemployment Rate', x = 'Region' , data = unemp)
plt.xticks(rotation = 40)
plt.show()
